support mccl test
Signed-off-by: Cyclinder Kuo <kuocyclinder@gmail.com>

diff --git a/rdma-tools/image/tools/rdmatools b/rdma-tools/image/tools/rdmatools
--- a/rdma-tools/image/tools/rdmatools
+++ b/rdma-tools/image/tools/rdmatools
@@ -3,147 +3,154 @@
 # Copyright 2024 Authors of spidernet-io
 # SPDX-License-Identifier: Apache-2.0
 
+GetInfinibandUpCa() {
+    CA_LIST=""
+    {
+        # this excludes other CA when shared rdma system
+        ALL_LOCAL_CA=$(ibdev2netdev | awk '{print $1}')
+        for NAME in ${ALL_LOCAL_CA}; do
+            { ibstatus ${NAME} | grep -E "state:.*ACTIVE" &>/dev/null; } || continue
+            if ibstatus ${NAME} | grep -E "link_layer:.*InfiniBand" &>/dev/null; then
+                CA_LIST="${CA_LIST} ${NAME}"
+            fi
+        done
+    } 1>&2
+    [ -n "${CA_LIST}" ] && { echo "${CA_LIST}" | tr ' ' '\n' | sed -E '/^$/ d'; }
+}
 
-GetInfinibandUpCa(){
-  CA_LIST=""
-  {
-    # this excludes other CA when shared rdma system
-    ALL_LOCAL_CA=$( ibdev2netdev | awk '{print $1}' )
-    for NAME in ${ALL_LOCAL_CA} ; do
-        { ibstatus ${NAME} | grep -E "state:.*ACTIVE" &>/dev/null ; } || continue
-        if ibstatus ${NAME} | grep -E "link_layer:.*InfiniBand" &>/dev/null ; then
+GetEthernetUpCa() {
+    CA_LIST=""
+    {
+        # this excludes other CA when shared rdma system
+        ALL_LOCAL_CA=$(ibdev2netdev | awk '{print $1}')
+        for NAME in ${ALL_LOCAL_CA}; do
+            { ibstatus ${NAME} | grep -E "state:.*ACTIVE" &>/dev/null; } || continue
+            if ibstatus ${NAME} | grep -E "link_layer:.*Ethernet" &>/dev/null; then
+                CA_LIST="${CA_LIST} ${NAME}"
+            fi
+        done
+    } 1>&2
+    [ -n "${CA_LIST}" ] && { echo "${CA_LIST}" | tr ' ' '\n' | sed -E '/^$/ d'; }
+}
+
+GetAllUpCa() {
+    CA_LIST=""
+    {
+        # this excludes other CA when shared rdma system
+        ALL_LOCAL_CA=$(ibdev2netdev | awk '{print $1}')
+        for NAME in ${ALL_LOCAL_CA}; do
+            { ibstatus ${NAME} | grep -E "state:.*ACTIVE" &>/dev/null; } || continue
             CA_LIST="${CA_LIST} ${NAME}"
-        fi
-    done
-  } 1>&2
-  [ -n "${CA_LIST}" ] && { echo "${CA_LIST}" | tr ' ' '\n' | sed -E '/^$/ d' ; }
+        done
+    } 1>&2
+    [ -n "${CA_LIST}" ] && { echo "${CA_LIST}" | tr ' ' '\n' | sed -E '/^$/ d'; }
 }
 
-GetEthernetUpCa(){
-  CA_LIST=""
-  {
-    # this excludes other CA when shared rdma system
-    ALL_LOCAL_CA=$(  ibdev2netdev | awk '{print $1}' )
-    for NAME in ${ALL_LOCAL_CA} ; do
-        { ibstatus ${NAME} | grep -E "state:.*ACTIVE" &>/dev/null ; } || continue
-        if ibstatus ${NAME} | grep -E "link_layer:.*Ethernet" &>/dev/null ; then
-            CA_LIST="${CA_LIST} ${NAME}"
-        fi
-    done
-  } 1>&2
-  [ -n "${CA_LIST}" ] && { echo "${CA_LIST}" | tr ' ' '\n' | sed -E '/^$/ d' ; }
-}
-
-GetAllUpCa(){
-  CA_LIST=""
-  {
-    # this excludes other CA when shared rdma system
-    ALL_LOCAL_CA=$(  ibdev2netdev | awk '{print $1}' )
-    for NAME in ${ALL_LOCAL_CA} ; do
-        { ibstatus ${NAME} | grep -E "state:.*ACTIVE" &>/dev/null ; } || continue
-        CA_LIST="${CA_LIST} ${NAME}"
-    done
-  } 1>&2
-  [ -n "${CA_LIST}" ] && { echo "${CA_LIST}" | tr ' ' '\n' | sed -E '/^$/ d' ; }
-}
-
-PrintAllInfinibandNetHosts(){
+PrintAllInfinibandNetHosts() {
     LOCA_IB_CA=$(GetInfinibandUpCa)
-    for CA_NAME in ${LOCA_IB_CA} ; do
+    for CA_NAME in ${LOCA_IB_CA}; do
         echo "------ ibhosts -C ${CA_NAME} "
-        INFO=$( ibhosts -C ${CA_NAME} 2>/dev/null )
+        INFO=$(ibhosts -C ${CA_NAME} 2>/dev/null)
         [ -n "${INFO}" ] && echo "${INFO}"
     done
 }
 
-PrintAllInfinibandAddress(){
+PrintAllInfinibandAddress() {
     LOCA_IB_CA=$(GetInfinibandUpCa)
-    for CA_NAME in ${LOCA_IB_CA} ; do
+    for CA_NAME in ${LOCA_IB_CA}; do
         echo "------ ibaddr -C ${CA_NAME} "
-        INFO=$( ibaddr -C ${CA_NAME} 2>/dev/null )
+        INFO=$(ibaddr -C ${CA_NAME} 2>/dev/null)
         [ -n "${INFO}" ] && echo "${INFO}"
     done
 }
 
-
-PrintAllInfinibandSubnet(){
+PrintAllInfinibandSubnet() {
     LOCA_IB_CA=$(GetInfinibandUpCa)
-    for CA_NAME in ${LOCA_IB_CA} ; do
+    for CA_NAME in ${LOCA_IB_CA}; do
         echo "------ ibdiagnet -i ${CA_NAME} "
-        INFO=$( ibdiagnet -i ${CA_NAME} 2>/dev/null )
+        INFO=$(ibdiagnet -i ${CA_NAME} 2>/dev/null)
         [ -n "${INFO}" ] && echo "${INFO}"
     done
 }
 
 #================================================================
 
-getUpInterfaceIP(){
-# output:
-# device     IP             Mask
-# net1       172.81.1.143   16
-  FILTER=${1:-""}
-  {
-      RESULT=""
-      DEV_LIST=$( ls /sys/class/net | grep -v lo )
-      for DEVNAME in ${DEV_LIST} ; do
-          { ip link show ${DEVNAME} | grep "state UP" &>/dev/null ; } || continue
-          if [ -n "${FILTER}" ] ; then
-                ( ip a s ${DEVNAME} | grep "${FILTER}" &>/dev/null ; ) || continue
-          fi
-          IP4_ADDR=$( ip r | grep -E "dev ${DEVNAME} .* src" |  awk '{print $NF}' | head -1 )
-          [ -n "${IP4_ADDR}" ] || continue
-          IP_MASK_LENGTH=$( ip a s ${DEVNAME} | grep -oP "(?<=inet\s)${IP4_ADDR}/[0-9]+" | awk -F'/' '{print $2}' )
-          RESULT="${RESULT}
+getUpInterfaceIP() {
+    # output:
+    # device     IP             Mask
+    # net1       172.81.1.143   16
+    FILTER=${1:-""}
+    {
+        RESULT=""
+        DEV_LIST=$(ls /sys/class/net | grep -v lo)
+        for DEVNAME in ${DEV_LIST}; do
+            { ip link show ${DEVNAME} | grep "state UP" &>/dev/null; } || continue
+            if [ -n "${FILTER}" ]; then
+                (ip a s ${DEVNAME} | grep "${FILTER}" &>/dev/null) || continue
+            fi
+            IP4_ADDR=$(ip r | grep -E "dev ${DEVNAME} .* src" | awk '{print $NF}' | head -1)
+            [ -n "${IP4_ADDR}" ] || continue
+            IP_MASK_LENGTH=$(ip a s ${DEVNAME} | grep -oP "(?<=inet\s)${IP4_ADDR}/[0-9]+" | awk -F'/' '{print $2}')
+            RESULT="${RESULT}
 ${DEVNAME} ${IP4_ADDR} ${IP_MASK_LENGTH}"
-      done
-  } 1>&2
-  [ -n "${RESULT}" ] && { echo "${RESULT}" | sed -E '/^$/ d' ; }
+        done
+    } 1>&2
+    [ -n "${RESULT}" ] && { echo "${RESULT}" | sed -E '/^$/ d'; }
 }
 
-
-GetUpEthernetIP(){
-# output:
-# device     IP             Mask
-# net1       172.81.1.143   16
-  getUpInterfaceIP "link/ether"
+GetUpEthernetIP() {
+    # output:
+    # device     IP             Mask
+    # net1       172.81.1.143   16
+    getUpInterfaceIP "link/ether"
 }
 
-GetUpInfinibandIP(){
-# output:
-# device     IP             Mask
-# net1       172.81.1.143   16
-  getUpInterfaceIP "link/infiniband"
+GetUpInfinibandIP() {
+    # output:
+    # device     IP             Mask
+    # net1       172.81.1.143   16
+    getUpInterfaceIP "link/infiniband"
 }
 
-GetUpAllIP(){
-# output:
-# device     IP             Mask
-# net1       172.81.1.143   16
-  getUpInterfaceIP
+GetDefaultGatewayNic() {
+    NIC=""
+    ROUTES=$(ip -j route get 8.8.8.8 2>/dev/null)
+    [ -n "${ROUTES}" ] && NIC=$(echo "${ROUTES}" | jq '.[].dev' | head -n1)
+    echo "${NIC}"
+}
+
+GetUpAllIP() {
+    # output:
+    # device     IP             Mask
+    # net1       172.81.1.143   16
+    getUpInterfaceIP
 }
 
 #======================================================
 
-GetLocalRoceDeviceIP(){
-# output:
-# device  interface  IP            Mask protocol  bset_index
-# mlx5_16 net1       172.81.1.143  16   RoceV2    3
+GetLocalRoceDeviceIP() {
+    # output:
+    # device  interface  IP            Mask protocol  bset_index
+    # mlx5_16 net1       172.81.1.143  16   RoceV2    3
     {
         # device  ip             index
         # mlx5_16 172.81.1.143   4
-        RAW_INFO=$( show_gids | grep -E "[0-9]+(\.[0-9]+){3}[[:space:]]+v2" | sed -E 's?^([^[:space:]]+)[[:space:]]+([^[:space:]]+)[[:space:]]+([^[:space:]]+)[[:space:]]+([^[:space:]]+)[[:space:]]+([^[:space:]]+)[[:space:]]+v2.*?\1 \5 \3?g' )
+        RAW_INFO=$(show_gids | grep -E "[0-9]+(\.[0-9]+){3}[[:space:]]+v2" | sed -E 's?^([^[:space:]]+)[[:space:]]+([^[:space:]]+)[[:space:]]+([^[:space:]]+)[[:space:]]+([^[:space:]]+)[[:space:]]+([^[:space:]]+)[[:space:]]+v2.*?\1 \5 \3?g')
 
         RESULT=""
         OLD=$IFS
         IFS=$'\n'
-        for ITEM in ${RAW_INFO} ;do
-            RDMA_DEVICE=$( echo "$ITEM" | awk  '{print $1}' )
-            RDMA_ADDR=$( echo "$ITEM" | awk  '{print $2}' )
-            RDMA_INDEX=$( echo "$ITEM" | awk  '{print $3}' )
+        for ITEM in ${RAW_INFO}; do
+            RDMA_DEVICE=$(echo "$ITEM" | awk '{print $1}')
+            RDMA_ADDR=$(echo "$ITEM" | awk '{print $2}')
+            RDMA_INDEX=$(echo "$ITEM" | awk '{print $3}')
 
-            INTERFACE_NAME=$( ip r | grep "src ${RDMA_ADDR}" | grep -Eo " dev [^[:space:]]+ " | awk '{print $2}' | head -1 )
-            [ -n "${INTERFACE_NAME}" ] || { echo "failed to find interface for rdma device ${RDMA_DEVICE} " ; continue ;  }
-            IP_MASK_LENGTH=$( ip a s ${INTERFACE_NAME} | grep -oP "(?<=inet\s)${RDMA_ADDR}/[0-9]+" | awk -F'/' '{print $2}' )
+            INTERFACE_NAME=$(ip r | grep "src ${RDMA_ADDR}" | grep -Eo " dev [^[:space:]]+ " | awk '{print $2}' | head -1)
+            [ -n "${INTERFACE_NAME}" ] || {
+                echo "failed to find interface for rdma device ${RDMA_DEVICE} "
+                continue
+            }
+            IP_MASK_LENGTH=$(ip a s ${INTERFACE_NAME} | grep -oP "(?<=inet\s)${RDMA_ADDR}/[0-9]+" | awk -F'/' '{print $2}')
             RESULT="${RESULT}
 ${RDMA_DEVICE} ${INTERFACE_NAME} ${RDMA_ADDR} ${IP_MASK_LENGTH}  RoceV2 ${RDMA_INDEX}"
         done
@@ -152,82 +159,81 @@ ${RDMA_DEVICE} ${INTERFACE_NAME} ${RDMA_ADDR} ${IP_MASK_LENGTH}  RoceV2 ${RDMA_I
     [ -n "${RESULT}" ] && echo "${RESULT}"
 }
 
-GetLocalIBDeviceIP(){
+GetLocalIBDeviceIP() {
     # output:
     # device  interface  IP            Mask protocol      bset_index
     # mlx5_16 net1       172.81.1.143  16   infiniband    0
     {
         RESULT=""
         IB_DEV_LIST=$(GetInfinibandUpCa)
-        for CA_NAME in ${IB_DEV_LIST} ; do
-            INTERFACE_NAME=$( ibdev2netdev | grep "${CA_NAME} " | awk '{print $5}' )
-            RDMA_ADDR=$( ip r | grep -E "dev ${INTERFACE_NAME} .* src" |  awk '{print $NF}' | head -1 )
+        for CA_NAME in ${IB_DEV_LIST}; do
+            INTERFACE_NAME=$(ibdev2netdev | grep "${CA_NAME} " | awk '{print $5}')
+            RDMA_ADDR=$(ip r | grep -E "dev ${INTERFACE_NAME} .* src" | awk '{print $NF}' | head -1)
             [ -n "${RDMA_ADDR}" ] || continue
-            IP_MASK_LENGTH=$( ip a s ${INTERFACE_NAME} | grep -oP "(?<=inet\s)${RDMA_ADDR}/[0-9]+" | awk -F'/' '{print $2}' )
+            IP_MASK_LENGTH=$(ip a s ${INTERFACE_NAME} | grep -oP "(?<=inet\s)${RDMA_ADDR}/[0-9]+" | awk -F'/' '{print $2}')
             RESULT="${RESULT}
 ${CA_NAME} ${INTERFACE_NAME} ${RDMA_ADDR} ${IP_MASK_LENGTH} infiniband 0"
         done
     } 1>&2
-    [ -n "${RESULT}" ] && { echo "${RESULT}" | sed -E '/^$/ d' ; }
+    [ -n "${RESULT}" ] && { echo "${RESULT}" | sed -E '/^$/ d'; }
 }
 
-GetLocalRdmaDeviceIP(){
+GetLocalRdmaDeviceIP() {
     GetLocalRoceDeviceIP || true
     GetLocalIBDeviceIP || true
 }
 
-CheckIPv4SameSubnet(){
-  {
-    ipa=${1:-""}
-    ipb=${2:-""}
-    length=${3:-""}
+CheckIPv4SameSubnet() {
+    {
+        ipa=${1:-""}
+        ipb=${2:-""}
+        length=${3:-""}
 
-    if ! grep -E "^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$" <<< "$ipa"  &>/dev/null   ; then
-        echo "error, $ipa is not a ip address with format xx.yy.aa.bb"
-        exit -1
-    fi
-    if ! grep -E "^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$" <<< "$ipb"  &>/dev/null   ; then
-        echo "error, $ipb is not a ip address with format xx.yy.aa.bb"
-        exit -1
-    fi
-    if ! (( length>=1 && length <=32 )) ; then
-        echo "error, wrong length "
-        exit -1
-    fi
-    if ((length==32)) ; then
-        [ "$ipa" != "$ipb" ] && return 1
-        return 0
-    fi
+        if ! grep -E "^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$" <<<"$ipa" &>/dev/null; then
+            echo "error, $ipa is not a ip address with format xx.yy.aa.bb"
+            exit -1
+        fi
+        if ! grep -E "^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$" <<<"$ipb" &>/dev/null; then
+            echo "error, $ipb is not a ip address with format xx.yy.aa.bb"
+            exit -1
+        fi
+        if ! ((length >= 1 && length <= 32)); then
+            echo "error, wrong length "
+            exit -1
+        fi
+        if ((length == 32)); then
+            [ "$ipa" != "$ipb" ] && return 1
+            return 0
+        fi
 
-    ipa_val=0
-    for loop in ${ipa//./ } ; do
-        ((ipa_val= (ipa_val<<8) + loop))
-    done
-    ipb_val=0
-    for loop in ${ipb//./ } ; do
-        ((ipb_val= (ipb_val<<8) +loop))
-    done
+        ipa_val=0
+        for loop in ${ipa//./ }; do
+            ((ipa_val = (ipa_val << 8) + loop))
+        done
+        ipb_val=0
+        for loop in ${ipb//./ }; do
+            ((ipb_val = (ipb_val << 8) + loop))
+        done
 
-    (( MASK = 0xffffffff - ( (0x1<< (32-length) ) - 1 ) ))
-    if (( (ipa_val & MASK) == ( ipb_val & MASK) )) ; then
-        #echo "two IP are in a same subnet"
-        return 0
-    else
-        #echo "two IP are not in a same subnet"
-        return 1
-    fi
-  } 1>&2
+        ((MASK = 0xffffffff - ((0x1 << (32 - length)) - 1)))
+        if (((ipa_val & MASK) == (ipb_val & MASK))); then
+            #echo "two IP are in a same subnet"
+            return 0
+        else
+            #echo "two IP are not in a same subnet"
+            return 1
+        fi
+    } 1>&2
 }
 
-
-GetGPUAmount(){
+GetGPUAmount() {
     GPU_TOTAL=""
     {
-        if nvidia-smi -L &>/dev/null ; then
-            GPU_TOTAL=$( nvidia-smi -L  | wc -l )
-            if ((  GPU_TOTAL == 0 )) ; then
-                  echo "error, there is no GPU detected "
-                  return 1
+        if nvidia-smi -L &>/dev/null; then
+            GPU_TOTAL=$(nvidia-smi -L | wc -l)
+            if ((GPU_TOTAL == 0)); then
+                echo "error, there is no GPU detected "
+                return 1
             fi
         else
             echo "error, there is no GPU detected"
@@ -237,24 +243,46 @@ GetGPUAmount(){
     echo "${GPU_TOTAL}"
 }
 
-
-GetRdmaDevList(){
+GetMXGPUAmount() {
+    GPU_TOTAL=""
     {
-        DEV_LIST=$( ibdev2netdev | awk '{print $1}' | tr '\n' ' ' )
-        [ -n "${DEV_LIST}" ] || { echo "error, no rdma device is detected " ; exit 1 ; }
+        if mx-smi -L &>/dev/null; then
+            GPU_TOTAL=$(mx-smi -L | grep GPU- | wc -l)
+            if ((GPU_TOTAL == 0)); then
+                echo "error, there is no GPU detected "
+                return 1
+            fi
+        else
+            echo "error, there is no GPU detected"
+            return 1
+        fi
+    } 1>&2
+    echo "${GPU_TOTAL}"
+}
+
+GetRdmaDevList() {
+    {
+        DEV_LIST=$(ibdev2netdev | awk '{print $1}' | tr '\n' ' ')
+        [ -n "${DEV_LIST}" ] || {
+            echo "error, no rdma device is detected "
+            exit 1
+        }
     } 1>&2
     echo "${DEV_LIST}"
 }
 
-CheckGpuIdValidity(){
+CheckGpuIdValidity() {
     {
         GPU_NUM=${1:-""}
-        grep -E "^[0-9]+$" <<< "${GPU_NUM}" &>/dev/null || { echo "error, ${GPU_NUM} is not a GPU id" ; exit 1 ;  }
-        if nvidia-smi -L &>/dev/null ; then
-            GPU_TOTAL=$( nvidia-smi -L  | wc -l )
-            if ((  GPU_NUM>(GPU_TOTAL-1) )) ; then
-                  echo "error, there is only ${GPU_TOTAL} gpu device, but the designated gpu number is ${GPU_NUM} "
-                  return 1
+        grep -E "^[0-9]+$" <<<"${GPU_NUM}" &>/dev/null || {
+            echo "error, ${GPU_NUM} is not a GPU id"
+            exit 1
+        }
+        if nvidia-smi -L &>/dev/null; then
+            GPU_TOTAL=$(nvidia-smi -L | wc -l)
+            if ((GPU_NUM > (GPU_TOTAL - 1))); then
+                echo "error, there is only ${GPU_TOTAL} gpu device, but the designated gpu number is ${GPU_NUM} "
+                return 1
             fi
         else
             echo "error, there is no GPU detected"
@@ -265,10 +293,10 @@ CheckGpuIdValidity(){
 }
 
 # todo: just support RoceV2, need to support inifiband
-CheckRdmaDevValidity(){
+CheckRdmaDevValidity() {
     {
         DEV_NAME=${1:-""}
-        if ibstat ${DEV_NAME} &>/dev/null ; then
+        if ibstat ${DEV_NAME} &>/dev/null; then
             return 0
         else
             echo "error, there is not rdma device ${DEV_NAME}"
@@ -277,15 +305,14 @@ CheckRdmaDevValidity(){
     } 1>&2
 }
 
-GetBestRdmaDeviceIP(){
+GetBestRdmaDeviceIP() {
     BEST_IP=""
     {
         DEV_NAME=${1:-""}
-        if CheckRdmaDevValidity ${DEV_NAME} &>/dev/null ; then
-            INTERFACE=$( ibdev2netdev  | grep -E "^${DEV_NAME} " | awk '{print $5}' )
-            BEST_IP=$( ip r | grep -E "dev ${INTERFACE} .* src" |  awk '{print $NF}' | head -1 )
+        if CheckRdmaDevValidity ${DEV_NAME} &>/dev/null; then
+            INTERFACE=$(ibdev2netdev | grep -E "^${DEV_NAME} " | awk '{print $5}')
+            BEST_IP=$(ip r | grep -E "dev ${INTERFACE} .* src" | awk '{print $NF}' | head -1)
         fi
     } 1>&2
     echo "${BEST_IP}"
 }
-
diff --git a/rdma-tools/image/tools/testGpuBw b/rdma-tools/image/tools/testGpuBw
--- a/rdma-tools/image/tools/testGpuBw
+++ b/rdma-tools/image/tools/testGpuBw
@@ -8,29 +8,39 @@
 set -o errexit
 set -o nounset
 
-source /usr/sbin/rdmatools
-GPU_NUM=$( GetGPUAmount )
+COMMAND_LIST=${COMMAND_LIST:-"bandwidthTest"}
+for ITEM in ${COMMAND_LIST}; do
+  if ! which ${ITEM} &>/dev/null; then
+    echo "error, ${ITEM} tools not found"
+    exit 1
+  fi
+done
 
-(( GPU_NUM > 0 )) || { echo "error, there is no GPU detected" ; exit 1 ; }
+source /usr/sbin/rdmatools
+GPU_NUM=$(GetGPUAmount)
+
+((GPU_NUM > 0)) || {
+  echo "error, there is no GPU detected"
+  exit 1
+}
 echo "there is ${GPU_NUM} GPU locally"
 
-RunTest(){
+RunTest() {
   CMD=${1:-""}
-  for (( N=0 ; N < GPU_NUM; N++)); do
-        echo ""
-        echo "***************************************************************************************************************"
-        echo "********************                     ${CMD}  on GPU ${N}            ****************************************"
-        echo "***************************************************************************************************************"
-        eval ${CMD} --device=${N} || exit 1
-        echo ""
+  for ((N = 0; N < GPU_NUM; N++)); do
+    echo ""
+    echo "***************************************************************************************************************"
+    echo "********************                     ${CMD}  on GPU ${N}            ****************************************"
+    echo "***************************************************************************************************************"
+    eval ${CMD} --device=${N} || exit 1
+    echo ""
   done
 }
 
-for ITEM in "bandwidthTest" ; do
-    echo "------------------------- ${ITEM} ---------------------------------------"
-    RunTest "${ITEM}"
+for ITEM in "bandwidthTest"; do
+  echo "------------------------- ${ITEM} ---------------------------------------"
+  RunTest "${ITEM}"
 done
-
 
 echo "***************************************************************************************************************"
 echo "********************                   nvbandwidth on all GPU          ****************************************"
diff --git a/rdma-tools/image/tools/testNcclTest b/rdma-tools/image/tools/testNcclTest
--- a/rdma-tools/image/tools/testNcclTest
+++ b/rdma-tools/image/tools/testNcclTest
@@ -8,16 +8,27 @@
 set -o errexit
 set -o nounset
 
+# nccl test requires nvidia-smi tools, if nvidia-smi tools not exist, exit 1
+if ! which nvidia-smi &>/dev/null; then
+   echo "error, nvidia-smi tools not found"
+   exit 1
+fi
 
 source /usr/sbin/rdmatools
-GPU_NUM=$( GetGPUAmount )
-(( GPU_NUM > 0 )) || { echo "error, there is no GPU detected" ; exit 1 ; }
+GPU_NUM=$(GetGPUAmount)
+((GPU_NUM > 0)) || {
+   echo "error, there is no GPU detected"
+   exit 1
+}
 echo "there is ${GPU_NUM} GPU locally"
 
-POD_IP_LIST=$( getAllEndpoints 2>/dev/null )
-POD_NUM=$( echo "${POD_IP_LIST}" | wc -l )
-HOST_LIST=$( echo -n "${POD_IP_LIST}" | tr '\n' ',' )
-(( POD_NUM > 0 )) || { echo "error, failed to detect pods" ; exit 1 ; }
+POD_IP_LIST=$(getAllEndpoints 2>/dev/null)
+POD_NUM=$(echo "${POD_IP_LIST}" | wc -l)
+HOST_LIST=$(echo -n "${POD_IP_LIST}" | tr '\n' ',')
+((POD_NUM > 0)) || {
+   echo "error, failed to detect pods"
+   exit 1
+}
 echo "HOST_LIST: ${HOST_LIST}"
 
 CMD_NAME=${CMD_NAME:-"all_reduce_perf"}
@@ -31,8 +42,8 @@ echo "********************  nccl-test: mpirun for ${CMD_NAME}                   
 echo "********************              hcoll: disabled                                      ************************"
 echo "***************************************************************************************************************"
 
-HOST_SLOT=$( echo -n "${HOST_LIST}" | tr ',' "\n" | sed -E 's?(.*)?\1:'${GPU_NUM}'?g' | tr '\n' ',' )
-PARAMETERS=" -np $(( POD_NUM * GPU_NUM )) -H ${HOST_SLOT}  \
+HOST_SLOT=$(echo -n "${HOST_LIST}" | tr ',' "\n" | sed -E 's?(.*)?\1:'${GPU_NUM}'?g' | tr '\n' ',')
+PARAMETERS=" -np $((POD_NUM * GPU_NUM)) -H ${HOST_SLOT}  \
    --bind-to none \
    -x PATH \
    -x LD_LIBRARY_PATH \
@@ -65,7 +76,6 @@ echo ""
 echo " mpirun ${OPTIONS} "
 echo ""
 mpirun ${OPTIONS}
-
 
 echo ""
 echo "-----------------------------   run with enabling GDR and gdrCopy -------------------------------"
diff --git a/rdma-tools/image/tools/testRemoteGpu b/rdma-tools/image/tools/testRemoteGpu
--- a/rdma-tools/image/tools/testRemoteGpu
+++ b/rdma-tools/image/tools/testRemoteGpu
@@ -6,20 +6,24 @@
 # ib_write_bw with GDR : test GDR: local node against a remote node , with rdma device in the same subnet
 # todo: support infiniband
 
-
 #set -x
 #set -o pipefail
 set -o errexit
 set -o nounset
 
+if ! which ib_write_bw &>/dev/null; then
+    echo "error, ib_write_bw tools not found"
+    exit 1
+fi
+
 REMOTE_IP=${1:-""}
 
 source /usr/sbin/rdmatools
-[ -n "${REMOTE_IP}" ] || REMOTE_IP=$( getOneRemoteEndpoint )
+[ -n "${REMOTE_IP}" ] || REMOTE_IP=$(getOneRemoteEndpoint)
 
 CMD_OPTIONS=${CMD_OPTIONS:-"-a -F --report_gbits -q 1"}
 
-TestPerftestGpu(){
+TestPerftestGpu() {
 
     echo ""
     echo "***************************************************************************************************************"
@@ -27,22 +31,28 @@ TestPerftestGpu(){
     echo "***************************************************************************************************************"
     echo ""
 
-    GPU_TOTAL=$( GetGPUAmount ) || { echo "error, there is no GPU locally" ; exit 1 ; }
-    RDMA_DEV_LIST=$( GetRdmaDevList ) || { echo "error, there is RDMA device locally" ; exit 1 ; }
+    GPU_TOTAL=$(GetGPUAmount) || {
+        echo "error, there is no GPU locally"
+        exit 1
+    }
+    RDMA_DEV_LIST=$(GetRdmaDevList) || {
+        echo "error, there is RDMA device locally"
+        exit 1
+    }
 
     echo "---------local 127.0.0.1 topo:"
     nvidia-smi topo -m || true
     GetLocalRdmaDeviceIP
     echo ""
-    echo "GPU range: 0 ... $((GPU_TOTAL-1))"
+    echo "GPU range: 0 ... $((GPU_TOTAL - 1))"
     while :; do
-      echo ""
-      echo -n "Please input the expected GPU number of local node: "
-      read LOCAL_GPU_NUM
-      if [ -n "${LOCAL_GPU_NUM}" ] ; then
-         CheckGpuIdValidity "${LOCAL_GPU_NUM}" || continue
-         break
-      fi
+        echo ""
+        echo -n "Please input the expected GPU number of local node: "
+        read LOCAL_GPU_NUM
+        if [ -n "${LOCAL_GPU_NUM}" ]; then
+            CheckGpuIdValidity "${LOCAL_GPU_NUM}" || continue
+            break
+        fi
     done
     echo ""
     show_gids
@@ -52,30 +62,38 @@ TestPerftestGpu(){
         echo ""
         echo -n "Please input the expected RDMA device of local node: "
         read LOCAL_RDMA_DEV
-        if [ -n "${LOCAL_RDMA_DEV}" ] ; then
+        if [ -n "${LOCAL_RDMA_DEV}" ]; then
             CheckRdmaDevValidity "${LOCAL_RDMA_DEV}" || continue
             break
         fi
     done
     echo ""
-    LOCAL_RDMA_IP=$( GetBestRdmaDeviceIP "${LOCAL_RDMA_DEV}" )
-    [ -n "${LOCAL_RDMA_IP}" ] || { echo "error, failed to find any IP on device ${LOCAL_RDMA_DEV}" ; exit 1 ;  }
-    LOCAL_INTERFACE=$( ibdev2netdev  | grep -E "^${LOCAL_RDMA_DEV} " | awk '{print $5}'  )
+    LOCAL_RDMA_IP=$(GetBestRdmaDeviceIP "${LOCAL_RDMA_DEV}")
+    [ -n "${LOCAL_RDMA_IP}" ] || {
+        echo "error, failed to find any IP on device ${LOCAL_RDMA_DEV}"
+        exit 1
+    }
+    LOCAL_INTERFACE=$(ibdev2netdev | grep -E "^${LOCAL_RDMA_DEV} " | awk '{print $5}')
 
-
-    GPU_TOTAL=$( ssh ${REMOTE_IP} " source /usr/sbin/rdmatools && GetGPUAmount " ) || { echo "error, there is no GPU on remote ${REMOTE_IP}" ; exit 1 ; }
-    RDMA_DEV_LIST=$( ssh ${REMOTE_IP} " source /usr/sbin/rdmatools && GetRdmaDevList " ) || { echo "error, there is RDMA device on remote ${REMOTE_IP}" ; exit 1 ; }
+    GPU_TOTAL=$(ssh ${REMOTE_IP} " source /usr/sbin/rdmatools && GetGPUAmount ") || {
+        echo "error, there is no GPU on remote ${REMOTE_IP}"
+        exit 1
+    }
+    RDMA_DEV_LIST=$(ssh ${REMOTE_IP} " source /usr/sbin/rdmatools && GetRdmaDevList ") || {
+        echo "error, there is RDMA device on remote ${REMOTE_IP}"
+        exit 1
+    }
     echo ""
     echo "---------remote ${REMOTE_IP} topo:"
     ssh ${REMOTE_IP} " nvidia-smi topo -m || true "
     ssh ${REMOTE_IP} " source /usr/sbin/rdmatools && GetLocalRdmaDeviceIP "
     echo ""
-    echo "GPU range: 0 ... $((GPU_TOTAL-1))"
+    echo "GPU range: 0 ... $((GPU_TOTAL - 1))"
     while :; do
         echo ""
         echo -n "Please input the expected GPU number of remote node ${REMOTE_IP}: "
         read REMOTE_GPU_NUM
-        if [ -n "${REMOTE_GPU_NUM}" ] ; then
+        if [ -n "${REMOTE_GPU_NUM}" ]; then
             ssh ${REMOTE_IP} " source /usr/sbin/rdmatools && CheckGpuIdValidity ${REMOTE_GPU_NUM}  " || continue
             break
         fi
@@ -88,13 +106,16 @@ TestPerftestGpu(){
         echo ""
         echo -n "Please input the expected RDMA device of remote node ${REMOTE_IP}: "
         read REMOTE_RDMA_DEV
-        if [ -n "${REMOTE_RDMA_DEV}" ] ; then
+        if [ -n "${REMOTE_RDMA_DEV}" ]; then
             ssh ${REMOTE_IP} " source /usr/sbin/rdmatools && CheckRdmaDevValidity ${REMOTE_RDMA_DEV}  " || continue
             break
         fi
     done
-    REMOTE_RDMA_IP=$(  ssh ${REMOTE_IP} " source /usr/sbin/rdmatools && GetBestRdmaDeviceIP ${REMOTE_RDMA_DEV}  " )
-    [ -n "${REMOTE_RDMA_IP}" ] || { echo "error, failed to find any IP on device ${REMOTE_RDMA_IP}" ; exit 1 ;  }
+    REMOTE_RDMA_IP=$(ssh ${REMOTE_IP} " source /usr/sbin/rdmatools && GetBestRdmaDeviceIP ${REMOTE_RDMA_DEV}  ")
+    [ -n "${REMOTE_RDMA_IP}" ] || {
+        echo "error, failed to find any IP on device ${REMOTE_RDMA_IP}"
+        exit 1
+    }
 
     echo ""
     echo "---------------------------------------------------------------------------------------------------------"
@@ -103,21 +124,21 @@ TestPerftestGpu(){
     echo "            remote node ${REMOTE_IP} : GPU ${REMOTE_GPU_NUM}, device ${REMOTE_RDMA_DEV}"
     echo "----------------------------------------------------------------------------------------------------------"
 
-    if ! ping -I ${LOCAL_INTERFACE} -c 2 ${REMOTE_RDMA_IP} &>/dev/null ; then
+    if ! ping -I ${LOCAL_INTERFACE} -c 2 ${REMOTE_RDMA_IP} &>/dev/null; then
         echo "error, failed to ping remote ${REMOTE_RDMA_IP} from local interface ${LOCAL_INTERFACE}"
         exit 1
     fi
 
     (
-        PID=`ps aux | grep ib_write_bw | grep -v grep | awk '{print $2}' ` && [ -n "${PID}" ] && kill -9 ${PID}
+        PID=$(ps aux | grep ib_write_bw | grep -v grep | awk '{print $2}') && [ -n "${PID}" ] && kill -9 ${PID}
         echo "server on local: ib_write_bw -d ${LOCAL_RDMA_DEV} --use_cuda=${LOCAL_GPU_NUM} ${CMD_OPTIONS}  "
         ib_write_bw -d ${LOCAL_RDMA_DEV} --use_cuda=${LOCAL_GPU_NUM} ${CMD_OPTIONS}
-    )&
+    ) &
     sleep 3
 
     echo "clinet on remote ${REMOTE_IP}: ib_write_bw -d ${REMOTE_RDMA_DEV} --use_cuda=${REMOTE_GPU_NUM} ${CMD_OPTIONS}  ${LOCAL_RDMA_IP} "
     #ssh ${REMOTE_IP}  " ulimit -l 2000000 && ib_write_bw -d ${REMOTE_RDMA_DEV} --use_cuda=${REMOTE_GPU_NUM} ${CMD_OPTIONS} ${LOCAL_RDMA_IP} "
-    ssh ${REMOTE_IP}  " ib_write_bw -d ${REMOTE_RDMA_DEV} --use_cuda=${REMOTE_GPU_NUM} ${CMD_OPTIONS} ${LOCAL_RDMA_IP} "
+    ssh ${REMOTE_IP} " ib_write_bw -d ${REMOTE_RDMA_DEV} --use_cuda=${REMOTE_GPU_NUM} ${CMD_OPTIONS} ${LOCAL_RDMA_IP} "
 
 }
 TestPerftestGpu
