rdma-tools: use commit id as image tag (#18)
* rdma-tools: use commit id as image tag

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* rdma-tools: use commit id as image tag

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* rdma-tools: use commit id as image tag

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* rdma-tools: use commit id as image tag

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

---------

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

diff --git a/.github/workflows/callBuildImage.yaml b/.github/workflows/callBuildImage.yaml
--- a/.github/workflows/callBuildImage.yaml
+++ b/.github/workflows/callBuildImage.yaml
@@ -12,8 +12,9 @@ on:
       code_sha:
         required: true
         type: string
+      # if empty, use the commit id of dockerfile_dirctory
       image_tag:
-        required: true
+        required: false
         type: string
       push_image:
         required: true
@@ -65,10 +66,10 @@ jobs:
         continue-on-error: false
         run: |
           echo '${{ toJSON(github) }}'
-          if ${{ inputs.ref != '' }}; then
+          # when CI trigger by PR and call this yaml, it appears ${{ github.event_name == 'pull_request' }}
+          #if ${{ inputs.ref != '' }} ; then
               echo "call by workflow_call"
               echo "code_sha=${{ inputs.code_sha }}" >> $GITHUB_ENV
-              echo "image_tag=${{ inputs.image_tag }}" >> $GITHUB_ENV
               echo "push_image=${{ inputs.push_image }}" >> $GITHUB_ENV
               echo "image_name=${{ inputs.image_name }}" >> $GITHUB_ENV
               echo "dockerfile_dirctory=${{ inputs.dockerfile_dirctory }}" >> $GITHUB_ENV
@@ -81,10 +82,19 @@ jobs:
               # ghcr.io/spidernet-io/rdma-tools
               echo "image_full_name=${{ env.ONLINE_REGISTER }}/${org_name}/${{ inputs.image_name }}" >> $GITHUB_ENV
           
-          else
-              echo "unexpected event: ${{ github.event_name }}"
-              exit 1
-          fi
+              image_tag=${{ inputs.image_tag }}
+              if [ -n "${image_tag}" ]; then
+                 echo "image_tag=${{ inputs.image_tag }}" >> $GITHUB_ENV
+              else
+                 dockerfile_dirctory=${{ inputs.dockerfile_dirctory }}
+                 image_tag=$( git ls-tree --full-tree HEAD -- ${dockerfile_dirctory} | awk '{ print $3 }' )
+                 [ -n "${image_tag}" ] || { echo "error, failed to get image_tag from commit id"; exit 1 ; }
+                 echo "image_tag=${image_tag}" >> $GITHUB_ENV
+              fi
+          #else
+          #    echo "unexpected event: ${{ github.event_name }}"
+          #    exit 1
+          #fi
 
       - name: Checkout Source Code
         uses: actions/checkout@v4
