rdma tools: add nccl (#37)
* nccl

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* nccl

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* nccl

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* nccl

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* nccl

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* nccl

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* nccl

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* d

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* d

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* d

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* d

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* d

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* nccl

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* nccl

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* nccl

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* nccl

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* sd

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* sd

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* sd

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* sd

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* sd

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* sd

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* sd

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* sd

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* sd

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* sd

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* sd

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* sd

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* sd

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* sd

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* d

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* d

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* d

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* d

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* d

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* d

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* d

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* d

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* d

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* d

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* d

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* d

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* d

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* d

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* d

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* d

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* d

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* d

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* d

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* d

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

---------

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

diff --git a/.github/workflows/ImageRdmaTools.yaml b/.github/workflows/ImageRdmaTools.yaml
--- a/.github/workflows/ImageRdmaTools.yaml
+++ b/.github/workflows/ImageRdmaTools.yaml
@@ -3,6 +3,7 @@ name: Image Rdma Tools
 env:
   IMAGE_NAME: rdma-tools
   DOCKERFILE_PATH: rdma-tools/image
+  GEN_DOCKERFILE_SCRIPT: rdma-tools/image/generateDockerfile.sh
 
 on:
   push:
@@ -24,12 +25,6 @@ on:
         description: 'compile the image based on the sha or branch of code'
         required: true
         default: main
-      baseImageCudaVersion:
-        description: 'cuda verison for base image. refer to https://hub.docker.com/r/nvidia/cuda'
-        required: false
-      baseImageOSVersion:
-        description: 'os verison for base image. refer to https://hub.docker.com/r/nvidia/cuda'
-        required: false
 
 permissions: write-all
 
@@ -39,41 +34,34 @@ jobs:
     outputs:
       code_sha: ${{ env.code_sha }}
       push_image: ${{ env.push_image }}
-      image_name: ${{ env.image_name }}
       build_platform: ${{ env.build_platform }}
       upload_artifact: ${{ env.upload_artifact }}
-      dockerfile_dirctory: ${{ env.dockerfile_dirctory }}
-      baseImageFullName: ${{ env.baseImageFullName }}
       image_tag: ${{ env.image_tag }}
+      image_name: ${{ env.image_name }}
+      dockerfile_dirctory: ${{ env.dockerfile_dirctory }}
+      generateDockerfileScript: ${{ env.generateDockerfileScript }}
     steps:
       - name: get information
         run: |
           echo '${{ toJSON(github) }}'
+          echo "image_name=${{ env.IMAGE_NAME }}" >> $GITHUB_ENV
+          echo "build_platform=linux/amd64" >> $GITHUB_ENV
+          echo "upload_artifact=false" >> $GITHUB_ENV
+          echo "dockerfile_dirctory=${{ env.DOCKERFILE_PATH }}" >> $GITHUB_ENV
+          echo "generateDockerfileScript=${{ env.GEN_DOCKERFILE_SCRIPT }}" >> $GITHUB_ENV
           if ${{ github.event_name == 'workflow_dispatch' }}; then
             echo "call by workflow_dispatch"
             echo "code_sha=${{ github.event.inputs.ref }}" >> $GITHUB_ENV
             echo "push_image=true" >> $GITHUB_ENV
-            echo "image_name=${{ env.IMAGE_NAME }}" >> $GITHUB_ENV
-            echo "dockerfile_dirctory=${{ env.DOCKERFILE_PATH }}" >> $GITHUB_ENV
-            echo "build_platform=linux/amd64,linux/arm64" >> $GITHUB_ENV
-            echo "upload_artifact=false" >> $GITHUB_ENV
           elif ${{ github.event_name == 'push' }} ; then
             echo "call by push tag"
             echo "code_sha=${GITHUB_REF##*/}" >> $GITHUB_ENV
             echo "push_image=true" >> $GITHUB_ENV
-            echo "image_name=${{ env.IMAGE_NAME }}" >> $GITHUB_ENV
-            echo "dockerfile_dirctory=${{ env.DOCKERFILE_PATH }}" >> $GITHUB_ENV
-            echo "build_platform=linux/amd64,linux/arm64" >> $GITHUB_ENV
-            echo "upload_artifact=false" >> $GITHUB_ENV
           else
             echo "call by PR"
             echo "use sha ${{ github.event.pull_request.head.sha }} , by pr"
             echo "code_sha=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
             echo "push_image=false" >> $GITHUB_ENV
-            echo "image_name=${{ env.IMAGE_NAME }}" >> $GITHUB_ENV
-            echo "dockerfile_dirctory=${{ env.DOCKERFILE_PATH }}" >> $GITHUB_ENV
-            echo "build_platform=linux/amd64" >> $GITHUB_ENV
-            echo "upload_artifact=false" >> $GITHUB_ENV
           fi
 
       - name: Checkout Source Code
@@ -82,33 +70,15 @@ jobs:
           persist-credentials: false
           ref: ${{ env.code_sha }}
 
-      - name: Getting Build Arg
-        id: arg
+      - name: Generate Dockerfile
         run: |
           set -x
-          echo "get base image"
-          if [ -n "${{ github.event.inputs.baseImageCudaVersion }}" ] ; then
-              baseImageCudaVersion=${{ github.event.inputs.baseImageCudaVersion }}
-          fi
-          if [ -n "${{ github.event.inputs.baseImageOSVersion }}" ] ; then
-              baseImageOSVersion=${{ github.event.inputs.baseImageOSVersion }}
-          fi
-          if [ -n "${baseImageCudaVersion}" ] && [ -n "${baseImageOSVersion}" ] ; then
-              export BASEIMAGE_CUDA_VERISON=${baseImageCudaVersion}
-              export BASEIMAGE_OS_VERISON=${baseImageOSVersion}
-          fi
-          chmod +x ${{ env.DOCKERFILE_PATH }}/version.sh
-          source ${{ env.DOCKERFILE_PATH }}/version.sh
-          echo "baseImageFullName=${BASEIMAGE_FULL_NAME}" >> $GITHUB_ENV
-          echo "get image tag"
-          image_tag=${{ inputs.image_tag }}
-          if [ -n "${image_tag}" ]; then
-             echo "image_tag=${BASEIMAGE_CUDA_VERISON}-${{ inputs.image_tag }}" >> $GITHUB_ENV
-          else
-             image_tag=$( git ls-tree --full-tree HEAD -- ${{ env.DOCKERFILE_PATH }} | awk '{ print $3 }' )
-             [ -n "${image_tag}" ] || { echo "error, failed to get image_tag from commit id"; exit 1 ; }
-             echo "image_tag=${BASEIMAGE_CUDA_VERISON}-${image_tag}" >> $GITHUB_ENV
-          fi
+          cd ${{ env.DOCKERFILE_PATH }}
+          chmod +x ./generateDockerfile.sh
+          source ./generateDockerfile.sh
+          image_tag=$( git ls-tree --full-tree HEAD -- ${{ env.DOCKERFILE_PATH }} | awk '{ print $3 }' )
+          [ -n "${image_tag}" ] || { echo "error, failed to get image_tag from commit id"; exit 1 ; }
+          echo "image_tag=${ENV_BASEIMAGE_CUDA_VERISON}-${image_tag}" >> $GITHUB_ENV
 
   call-workflow:
     needs: [get_info]
@@ -120,6 +90,6 @@ jobs:
       dockerfile_dirctory: ${{ needs.get_info.outputs.dockerfile_dirctory }}
       build_platform: ${{ needs.get_info.outputs.build_platform }}
       upload_artifact: ${{ needs.get_info.outputs.upload_artifact }}
-      baseImageFullName: ${{ needs.get_info.outputs.baseImageFullName }}
       image_tag: ${{ needs.get_info.outputs.image_tag }}
+      generateDockerfileScript: ${{ needs.get_info.outputs.generateDockerfileScript }}
     secrets: inherit
diff --git a/.github/workflows/callBuildImage.yaml b/.github/workflows/callBuildImage.yaml
--- a/.github/workflows/callBuildImage.yaml
+++ b/.github/workflows/callBuildImage.yaml
@@ -30,8 +30,8 @@ on:
       upload_artifact:
         required: true
         type: string
-      baseImageFullName:
-        required: true
+      generateDockerfileScript:
+        required: false
         type: string
     outputs:
       imageArtifactName:
@@ -48,6 +48,23 @@ jobs:
     outputs:
       upload_image_artifact_name: ${{ env.upload_image_artifact_name }}
     steps:
+      - name: Free Disk Space (Ubuntu)
+        # https://github.com/spidernet-io/spiderpool/issues/3277
+        # https://github.com/actions/virtual-environments/issues/709
+        uses: jlumbroso/free-disk-space@main
+        with:
+          # this might remove tools that are actually needed,
+          # if set to "true" but frees about 6 GB
+          tool-cache: true
+          # all of these default to true, but feel free to set to
+          # "false" if necessary for your workflow
+          android: true
+          dotnet: true
+          haskell: true
+          large-packages: true
+          docker-images: true
+          swap-storage: true
+
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3.3.0
 
@@ -72,7 +89,6 @@ jobs:
           echo "dockerfile_dirctory=${{ inputs.dockerfile_dirctory }}" >> $GITHUB_ENV
           echo "build_platform=${{ inputs.build_platform }}" >> $GITHUB_ENV
           echo "upload_artifact=${{ inputs.upload_artifact }}" >> $GITHUB_ENV
-          echo "baseImageFullName=${{ inputs.baseImageFullName }}" >> $GITHUB_ENV
           echo "upload_image_artifact_name=image-$( date +%Y%m%d%H%M%S%N )" >> $GITHUB_ENV
           # spidernet-io/charts -> spidernet-io
           org_name=$( awk -F'/' '{print $1}'  <<< "${{ env.IMAGE_REPO }}" )
@@ -87,7 +103,6 @@ jobs:
           ref: ${{ env.code_sha }}
 
       - name: Getting Build Arg
-        id: arg
         run: |
           GIT_COMMIT_VERSION=$( git show -s --format='format:%H')
           GIT_COMMIT_TIME=$( git show -s --format='format:%aI')
@@ -101,6 +116,15 @@ jobs:
              image_tag=$( git ls-tree --full-tree HEAD -- ${dockerfile_dirctory} | awk '{ print $3 }' )
              [ -n "${image_tag}" ] || { echo "error, failed to get image_tag from commit id"; exit 1 ; }
              echo "image_tag=${image_tag}" >> $GITHUB_ENV
+          fi
+          GENERATE_SCRIPT_PATH=${{ inputs.generateDockerfileScript }}
+          if [ -n "${GENERATE_SCRIPT_PATH}" ]; then
+              [ -f "${GENERATE_SCRIPT_PATH}" ] || { echo "error, failed to find generateDockerfileScript: ${GENERATE_SCRIPT_PATH}"; exit 1 ; }
+              DIR_PATH=$( dirname ${GENERATE_SCRIPT_PATH} )
+              SCRIPT_NAME=$( basename ${GENERATE_SCRIPT_PATH} )
+              cd ${DIR_PATH}
+              chmod +x ${SCRIPT_NAME}
+              ./${SCRIPT_NAME}              
           fi
 
       - name: Login to online register
@@ -128,7 +152,6 @@ jobs:
             GIT_COMMIT_VERSION=${{ env.commitver }}
             GIT_COMMIT_TIME=${{ env.committime }}
             VERSION=${{ env.code_sha }}
-            BASE_IMAGE=${{ env.baseImageFullName }}
 
       # Upload artifact race images tar
       - name: Upload image tar
