merge tools (#130)
* merge tools

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* merge tools

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* merge tools

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* merge tools

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* merge tools

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* merge tools

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* merge tools

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* merge tools

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* merge tools

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* merge tools

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* merge tools

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* merge tools

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* merge tools

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* merge tools

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* merge tools

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* merge tools

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* merge tools

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* merge tools

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

* merge tools

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

---------

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

diff --git a/.github/workflows/ImageRdmaTools.yaml b/.github/workflows/ImageRdmaTools.yaml
--- a/.github/workflows/ImageRdmaTools.yaml
+++ b/.github/workflows/ImageRdmaTools.yaml
@@ -29,7 +29,7 @@ on:
 permissions: write-all
 
 jobs:
-  get_info:
+  get_nccl_info:
     runs-on: ubuntu-latest
     outputs:
       code_sha: ${{ env.code_sha }}
@@ -75,21 +75,86 @@ jobs:
           set -x
           cd ${{ env.DOCKERFILE_PATH }}
           chmod +x ./generateDockerfile.sh
-          source ./generateDockerfile.sh
+          VAR_NCCL_BASE=true ./generateDockerfile.sh
           image_tag=$( git ls-tree --full-tree HEAD -- ${{ env.DOCKERFILE_PATH }} | awk '{ print $3 }' )
           [ -n "${image_tag}" ] || { echo "error, failed to get image_tag from commit id"; exit 1 ; }
-          echo "image_tag=${ENV_BASEIMAGE_CUDA_VERISON}-${image_tag}" >> $GITHUB_ENV
+          echo "image_tag=${image_tag}" >> $GITHUB_ENV
 
-  call-workflow:
-    needs: [get_info]
+  call-nccl-workflow:
+    needs: [get_nccl_info]
     uses: ./.github/workflows/callBuildImage.yaml
     with:
-      code_sha: ${{ needs.get_info.outputs.code_sha }}
-      push_image: ${{ needs.get_info.outputs.push_image }}
-      image_name: ${{ needs.get_info.outputs.image_name }}
-      dockerfile_dirctory: ${{ needs.get_info.outputs.dockerfile_dirctory }}
-      build_platform: ${{ needs.get_info.outputs.build_platform }}
-      upload_artifact: ${{ needs.get_info.outputs.upload_artifact }}
-      image_tag: ${{ needs.get_info.outputs.image_tag }}
-      generateDockerfileScript: ${{ needs.get_info.outputs.generateDockerfileScript }}
+      code_sha: ${{ needs.get_nccl_info.outputs.code_sha }}
+      push_image: ${{ needs.get_nccl_info.outputs.push_image }}
+      image_name: ${{ needs.get_nccl_info.outputs.image_name }}
+      dockerfile_dirctory: ${{ needs.get_nccl_info.outputs.dockerfile_dirctory }}
+      build_platform: ${{ needs.get_nccl_info.outputs.build_platform }}
+      upload_artifact: ${{ needs.get_nccl_info.outputs.upload_artifact }}
+      image_tag: ${{ needs.get_nccl_info.outputs.image_tag }}
+      generateDockerfileCmd: "VAR_NCCL_BASE=true ${{ needs.get_nccl_info.outputs.generateDockerfileScript }}"
+    secrets: inherit
+
+  get_light_info:
+    runs-on: ubuntu-latest
+    outputs:
+      code_sha: ${{ env.code_sha }}
+      push_image: ${{ env.push_image }}
+      build_platform: ${{ env.build_platform }}
+      upload_artifact: ${{ env.upload_artifact }}
+      image_tag: ${{ env.image_tag }}
+      image_name: ${{ env.image_name }}
+      dockerfile_dirctory: ${{ env.dockerfile_dirctory }}
+      generateDockerfileScript: ${{ env.generateDockerfileScript }}
+    steps:
+      - name: get information
+        run: |
+          echo '${{ toJSON(github) }}'
+          echo "image_name=${{ env.IMAGE_NAME }}" >> $GITHUB_ENV
+          echo "build_platform=linux/amd64" >> $GITHUB_ENV
+          echo "upload_artifact=false" >> $GITHUB_ENV
+          echo "dockerfile_dirctory=${{ env.DOCKERFILE_PATH }}" >> $GITHUB_ENV
+          echo "generateDockerfileScript=${{ env.GEN_DOCKERFILE_SCRIPT }}" >> $GITHUB_ENV
+          if ${{ github.event_name == 'workflow_dispatch' }}; then
+            echo "call by workflow_dispatch"
+            echo "code_sha=${{ github.event.inputs.ref }}" >> $GITHUB_ENV
+            echo "push_image=true" >> $GITHUB_ENV
+          elif ${{ github.event_name == 'push' }} ; then
+            echo "call by push tag"
+            echo "code_sha=${GITHUB_REF##*/}" >> $GITHUB_ENV
+            echo "push_image=true" >> $GITHUB_ENV
+          else
+            echo "call by PR"
+            echo "use sha ${{ github.event.pull_request.head.sha }} , by pr"
+            echo "code_sha=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
+            echo "push_image=false" >> $GITHUB_ENV
+          fi
+
+      - name: Checkout Source Code
+        uses: actions/checkout@v4
+        with:
+          persist-credentials: false
+          ref: ${{ env.code_sha }}
+
+      - name: Generate Dockerfile
+        run: |
+          set -x
+          cd ${{ env.DOCKERFILE_PATH }}
+          chmod +x ./generateDockerfile.sh
+          VAR_NCCL_BASE=true ./generateDockerfile.sh
+          image_tag=$( git ls-tree --full-tree HEAD -- ${{ env.DOCKERFILE_PATH }} | awk '{ print $3 }' )
+          [ -n "${image_tag}" ] || { echo "error, failed to get image_tag from commit id"; exit 1 ; }
+          echo "image_tag=light-${image_tag}" >> $GITHUB_ENV
+
+  call-light-workflow:
+    needs: [get_light_info]
+    uses: ./.github/workflows/callBuildImage.yaml
+    with:
+      code_sha: ${{ needs.get_light_info.outputs.code_sha }}
+      push_image: ${{ needs.get_light_info.outputs.push_image }}
+      image_name: ${{ needs.get_light_info.outputs.image_name }}
+      dockerfile_dirctory: ${{ needs.get_light_info.outputs.dockerfile_dirctory }}
+      build_platform: ${{ needs.get_light_info.outputs.build_platform }}
+      upload_artifact: ${{ needs.get_light_info.outputs.upload_artifact }}
+      image_tag: ${{ needs.get_light_info.outputs.image_tag }}
+      generateDockerfileCmd: "VAR_NCCL_BASE=false ${{ needs.get_light_info.outputs.generateDockerfileScript }}"
     secrets: inherit
diff --git a/rdma-tools/image/tools/testRdmaPairLatency b/rdma-tools/image/tools/testRdmaPairLatency
--- a/rdma-tools/image/tools/testRdmaPairLatency
+++ b/rdma-tools/image/tools/testRdmaPairLatency
@@ -3,22 +3,24 @@
 # Copyright 2024 Authors of spidernet-io
 # SPDX-License-Identifier: Apache-2.0
 
-:<<EOF
-同时进行两两主机之间的打流测试，包括同轨和跨轨网卡打流，在两个主机之间打流时，
-    ASYNCHRONOUS=true 是让8个网卡同时打流，还是一个一个网卡打
-    SAME_NETWORK_TRACK=true 是 让同轨网卡打流，还是跨轨
 
-example1:
+:<<EOF
+脚本把 所有的主机，进行 两两 分组， 然后 并发的在 每一组主机之间 进行 正向和 反向的 同轨 RDMA 网卡 打流 
+    ASYNCHRONOUS=true           在每两个主机之间，是让 8 个网卡并发的同时打流，还是一个一个网卡顺序的打 （默认，顺序的打流）
+    SAME_NETWORK_TRACK=true     是 让同轨网卡打流，还是跨轨 （默认，同轨打 ）
+    LOOP_TIMES                  重复打几轮（默认1轮）
+
+test all endpoints :
     DURATION=30 LOOP_TIMES=2 ASYNCHRONOUS=true  SAME_NETWORK_TRACK=true testRdmaPair
 
-example2:
+test between specific endpoints:
     DURATION=10 LOOP_TIMES=1 ASYNCHRONOUS=false  testRdmaPair  "10.233.94.236  10.233.116.235 10.233.101.251"
 
-rdma cm:
-    DURATION=5  LOOP_TIMES=1 ASYNCHRONOUS=false ENABLE_RDMA_QOS=true RDMA_QOS=160 testRdmaPair  "10.0.0.10  10.0.0.2"
-
-exclude
+exclude endpoints:
     EXCLUDE_ENDPOINT="10.0.0.10 10.0.0.2" DURATION=10 LOOP_TIMES=1 ASYNCHRONOUS=false  testRdmaPair  
+
+rdma cm:
+    DURATION=5 ENABLE_RDMA_QOS=true RDMA_QOS=160 testRdmaPair
 
 EOF
 
@@ -37,12 +39,22 @@ CURRENT_FILENAME=$(basename $0)
 ENV_SSH_PORT=${ENV_SSH_PORT:-"2022"}
 EXCLUDE_ENDPOINT=${EXCLUDE_ENDPOINT:-""}
 
+BIDIRECTION=${BIDIRECTION:-"false"}
+
 source /usr/sbin/rdmatools
 source getAllEndpoints
+LOCAL_INT=$( ip r | grep default | head -1 | grep -oE "dev [^[:space:]]+"  | awk '{print $2}' )
+LOCAL_ENDPOINT_IP=$( ip -4 addr show ${LOCAL_INT} | grep -oP '(?<=inet\s)[0-9]+(\.[0-9]+){3}'	 )
+
 
 POD_IP_LIST=${1:-""}
 if [ -z "${POD_IP_LIST}" ] ;then 
     POD_IP_LIST=$(getOtherEndpoints 2>/dev/null) || true
+    POD_IP_LIST=$( echo "${POD_IP_LIST}" && echo "${LOCAL_ENDPOINT_IP}" )
+    POD_IP_LIST=$( echo "${POD_IP_LIST}" | sort )
+else 
+    POD_IP_LIST=$( echo "${POD_IP_LIST}"  | tr -s " " |  tr ' ' '\n' | tr -s '\n' )
+    POD_IP_LIST=$( echo "${POD_IP_LIST}" | sort )
 fi
 
 if [ -n "${EXCLUDE_ENDPOINT}" ]; then
@@ -50,7 +62,7 @@ if [ -n "${EXCLUDE_ENDPOINT}" ]; then
     TMP_LIST=""
     for ADDR in ${POD_IP_LIST} ; do
         ! grep " ${ADDR} " <<< " ${EXCLUDE_ENDPOINT} " &>/dev/null || { echo "exclude ${ADDR}" && continue ; }
-        TMP_LIST="${TMP_LIST} ${ADDR}"
+        TMP_LIST=$( echo "$TMP_LIST" && echo ${ADDR} )
     done
     POD_IP_LIST="${TMP_LIST}"
 fi
@@ -63,17 +75,28 @@ echo ""
     exit 1
 }
 
+TEST_POD_NUMBER=$( echo "${POD_IP_LIST}" | wc -l )
+if (( TEST_POD_NUMBER % 2 == 1 )) ; then
+    echo "error, pod number ${TEST_POD_NUMBER} must be even"
+    exit 1
+fi
+
 DEFAULT_LOCAL_INT=$( ip r | grep default | grep -Eo "dev .*" | awk '{print $2}' )
 LOCAL_IP=$( ip -4 addr show ${DEFAULT_LOCAL_INT} | grep -oP '(?<=inet\s)[0-9]+(\.[0-9]+){3}' | head -1 )
 
 WORKDIR="/tmp/${CURRENT_FILENAME}-$(date +%Y%m%d%H%M%S%N)"
 REMOTE_INFOR_DIR="${WORKDIR}/remoteip"
 REMOTE_OUTPUT_DIR="${WORKDIR}/output"
+TASK_FINISH_DIR="${WORKDIR}/ready"
 RESULT_DIR="${WORKDIR}/result"
 mkdir -p ${WORKDIR}
 mkdir -p ${REMOTE_INFOR_DIR}
 mkdir -p ${RESULT_DIR}
+rm -rf ${RESULT_DIR}/*
 mkdir -p ${REMOTE_OUTPUT_DIR}
+mkdir -p ${TASK_FINISH_DIR}
+
+echo "============== WORKDIR directory: ${WORKDIR} ===================="
 
 echo "collecting local information ..."
 LOCAL_RDMA_INFO=$(GetLocalRdmaDeviceIP)
@@ -81,13 +104,10 @@ LOCAL_RDMA_INFO=$(GetLocalRdmaDeviceIP)
     echo "error, failed to get local rdma information"
     exit 1
 }
-LOCAL_INT=$( ip r | grep default | head -1 | grep -oE "dev [^[:space:]]+"  | awk '{print $2}' )
-LOCAL_ENDPOINT_IP=$( ip -4 addr show ${LOCAL_INT} | grep -oP '(?<=inet\s)[0-9]+(\.[0-9]+){3}'	 )
-
 
 echo "collecting remote information ..."
 EXPECT_NUM=0
-for ADDR in ${POD_IP_LIST} ${LOCAL_ENDPOINT_IP}; do
+for ADDR in ${POD_IP_LIST}; do
     ((EXPECT_NUM += 1))
     (
         echo "collecting information from ${ADDR}"
@@ -111,6 +131,7 @@ echo "finished collectiong information in ${REMOTE_INFOR_DIR}"
 RunClient() {
     REMOTE_CLIENT="${1}"
     REMOTE_SERVER="${2}"
+    TASK_ROUND_ID="${3}"
     REMOTE_CLIENT_NAME=$( GetNodeName ${REMOTE_CLIENT} )
     REMOTE_SERVER_NAME=$( GetNodeName ${REMOTE_SERVER} )
 
@@ -123,7 +144,7 @@ RunClient() {
         echo "error, failed to find ${REMOTE_INFOR_DIR}/${REMOTE_SERVER} "
         exit 1
     }
-    RESULT_FILE="${RESULT_DIR}/${REMOTE_SERVER}"
+    RESULT_FILE="${RESULT_DIR}/round-${TASK_ROUND_ID}-${REMOTE_CLIENT}-to-${REMOTE_SERVER}"
 
     echo "" >>${RESULT_FILE}
     printf "________________________________________________________________________________________________________________________________________________\n" >>${RESULT_FILE}
@@ -133,6 +154,10 @@ RunClient() {
     REMOTE_RUN_OUTPUT_DIR="${REMOTE_OUTPUT_DIR}/${REMOTE_SERVER}"
     mkdir -p ${REMOTE_RUN_OUTPUT_DIR}
 
+    TASK_FINISH_SUBDIR="${TASK_FINISH_DIR}/${REMOTE_CLIENT}-to-${REMOTE_SERVER}"
+    mkdir -p ${TASK_FINISH_SUBDIR} || true 
+    rm -rf ${TASK_FINISH_SUBDIR}/*
+
     echo "-------------"
     cat ${REMOTE_INFOR_DIR}/${REMOTE_CLIENT}
     cat ${REMOTE_INFOR_DIR}/${REMOTE_SERVER}
@@ -140,8 +165,8 @@ RunClient() {
 
     # reset the port
     PORT=${START_PORT}
+    TASK_COUNTER=0
     while read LINE; do
-            echo "=== SERVER LINE: ${LINE}"
         REMOTE_DEVICE=$(echo "${LINE}" | awk '{print $1}')
         REMOTE_INTERFACE=$(echo "${LINE}" | awk '{print $2}')
         REMOTE_IP=$(echo "${LINE}" | awk '{print $3}')
@@ -154,7 +179,7 @@ RunClient() {
         #IFS=$'\n'
         while read CLIENT_LINE; do
             #IFS=$OLD
-            echo "=== CLIENT_LINE: ${CLIENT_LINE}"
+            echo "* CLIENT_LINE: ${CLIENT_LINE}"
             LOCAL_DEVICE=$(echo "${CLIENT_LINE}" | awk '{print $1}')
             LOCAL_INTERFACE=$(echo "${CLIENT_LINE}" | awk '{print $2}')
             LOCAL_IP=$(echo "${CLIENT_LINE}" | awk '{print $3}')
@@ -177,11 +202,11 @@ RunClient() {
                 [ "${SAME_TRACK}"x == "false"x ] || continue
             fi 
 
-            echo ""
-            echo "-------------------------------------------------------------------------------------------------"
-            echo "${CURRENT_FILENAME} case: client node ${REMOTE_CLIENT}/${REMOTE_CLIENT_NAME} ( ${LOCAL_INTERFACE} ${LOCAL_DEVICE} ${LOCAL_IP} ) and the server ${REMOTE_SERVER}/${REMOTE_SERVER_NAME} ( ${REMOTE_INTERFACE} ${REMOTE_DEVICE} ${REMOTE_IP} )  "
+            REMOTE_RUN_IP_OUTPUT_DIR="${REMOTE_RUN_OUTPUT_DIR}/${REMOTE_CLIENT}-${LOCAL_INTERFACE}-to-${REMOTE_SERVER}-${REMOTE_INTERFACE}"
 
-            REMOTE_RUN_IP_OUTPUT_DIR="${REMOTE_RUN_OUTPUT_DIR}/${REMOTE_IP}"
+            (( TASK_COUNTER = TASK_COUNTER + 1 ))
+            echo ""
+            echo "--------------- start case ${TASK_COUNTER}: client ${REMOTE_CLIENT_NAME}/${REMOTE_CLIENT} ( ${LOCAL_INTERFACE} ${LOCAL_DEVICE} ${LOCAL_IP} )  ===>   server ${REMOTE_SERVER_NAME}/${REMOTE_SERVER} ( ${REMOTE_INTERFACE} ${REMOTE_DEVICE} ${REMOTE_IP} )  --------------------- "
 
             MAX_SPEED=$(ethtool ${LOCAL_INTERFACE} | grep Speed | awk '{print $2}')
 
@@ -189,7 +214,8 @@ RunClient() {
             echo "client on ${REMOTE_CLIENT}/${REMOTE_CLIENT}: ${CMD_CLI} ${OPTIONS}"
             if [ "${ASYNCHRONOUS}"x == "true"x ]; then
                 (
-                    { ssh  -p ${ENV_SSH_PORT} ${REMOTE_CLIENT} "${CMD_CLI} ${OPTIONS}" | tee ${REMOTE_RUN_IP_OUTPUT_DIR}; } || true
+                    #{ ssh  -p ${ENV_SSH_PORT} ${REMOTE_CLIENT} "${CMD_CLI} ${OPTIONS}" | tee ${REMOTE_RUN_IP_OUTPUT_DIR}; } || true
+                    { ssh  -p ${ENV_SSH_PORT} ${REMOTE_CLIENT} "${CMD_CLI} ${OPTIONS}" > ${REMOTE_RUN_IP_OUTPUT_DIR}; } || true
                     BANDWITDH=$(cat ${REMOTE_RUN_IP_OUTPUT_DIR} | grep -A 1 "BW average" | grep -E "[0-9\.]+" | awk '{print $4 }') || true
                     PPS=$(cat ${REMOTE_RUN_IP_OUTPUT_DIR} | grep -A 1 "BW average" | grep -E "[0-9\.]+" | awk '{print $5 }') || true
                     if [ -n "${BANDWITDH}" ]; then
@@ -198,9 +224,12 @@ RunClient() {
                         echo "error, ${REMOTE_CLIENT}/${REMOTE_CLIENT_NAME}( ${LOCAL_INTERFACE} ${LOCAL_DEVICE} ${LOCAL_IP} ) failed to test server ${REMOTE_SERVER}/${REMOTE_SERVER_NAME} ( ${REMOTE_INTERFACE} ${REMOTE_DEVICE} ${REMOTE_IP} ${PORT} ) "
                         printf "%-40s\t%-40s\t%-20s%-20s%-20s%-20s\n" "${LOCAL_INTERFACE}/${LOCAL_DEVICE}/${LOCAL_IP}" "${REMOTE_INTERFACE}/${REMOTE_DEVICE}/${REMOTE_IP}" "0" "0" "${MAX_SPEED} ${SAME_TRACK}" >>${RESULT_FILE}
                     fi
+                    touch ${TASK_FINISH_SUBDIR}/${REMOTE_CLIENT}-${LOCAL_INTERFACE}-to-${REMOTE_SERVER}-${REMOTE_INTERFACE}
+                    echo "--------------- finish case ${TASK_COUNTER}: client ${REMOTE_CLIENT_NAME}/${REMOTE_CLIENT} ( ${LOCAL_INTERFACE} ${LOCAL_DEVICE} ${LOCAL_IP} )  ===>   server ${REMOTE_SERVER_NAME}/${REMOTE_SERVER} ( ${REMOTE_INTERFACE} ${REMOTE_DEVICE} ${REMOTE_IP} )  --------------------- "
                 )&
             else
-                { ssh  -p ${ENV_SSH_PORT} ${REMOTE_CLIENT} " ${CMD_CLI} ${OPTIONS}" | tee ${REMOTE_RUN_IP_OUTPUT_DIR}; } || true
+                #{ ssh  -p ${ENV_SSH_PORT} ${REMOTE_CLIENT} " ${CMD_CLI} ${OPTIONS}" | tee ${REMOTE_RUN_IP_OUTPUT_DIR}; } || true
+                { ssh  -p ${ENV_SSH_PORT} ${REMOTE_CLIENT} " ${CMD_CLI} ${OPTIONS}" > ${REMOTE_RUN_IP_OUTPUT_DIR}; } || true
                 BANDWITDH=$(cat ${REMOTE_RUN_IP_OUTPUT_DIR} | grep -A 1 "BW average" | grep -E "[0-9\.]+" | awk '{print $4 }') || true
                 PPS=$(cat ${REMOTE_RUN_IP_OUTPUT_DIR} | grep -A 1 "BW average" | grep -E "[0-9\.]+" | awk '{print $5 }') || true
                 if [ -n "${BANDWITDH}" ]; then
@@ -209,11 +238,13 @@ RunClient() {
                     echo "error, ${REMOTE_CLIENT}/${REMOTE_CLIENT_NAME}( ${LOCAL_INTERFACE} ${LOCAL_DEVICE} ${LOCAL_IP} ) failed to test server ${REMOTE_SERVER}/${REMOTE_SERVER_NAME} ( ${REMOTE_INTERFACE} ${REMOTE_DEVICE} ${REMOTE_IP} ${PORT} ) "
                     printf "%-40s\t%-40s\t%-20s%-20s%-20s%-20s\n" "${LOCAL_INTERFACE}/${LOCAL_DEVICE}/${LOCAL_IP}" "${REMOTE_INTERFACE}/${REMOTE_DEVICE}/${REMOTE_IP}" "0" "0" "${MAX_SPEED} ${SAME_TRACK}" >>${RESULT_FILE}
                 fi
+                touch ${TASK_FINISH_SUBDIR}/${REMOTE_CLIENT}-${LOCAL_INTERFACE}-to-${REMOTE_SERVER}-${REMOTE_INTERFACE}
+                echo "--------------- finish case ${TASK_COUNTER}: client ${REMOTE_CLIENT_NAME}/${REMOTE_CLIENT} ( ${LOCAL_INTERFACE} ${LOCAL_DEVICE} ${LOCAL_IP} )  ===>   server ${REMOTE_SERVER_NAME}/${REMOTE_SERVER} ( ${REMOTE_INTERFACE} ${REMOTE_DEVICE} ${REMOTE_IP} )  --------------------- "
             fi
+            echo ""
 
         done <${REMOTE_INFOR_DIR}/${REMOTE_CLIENT}
 
-        echo "======= next server device"
         (( PORT = PORT + 1))
     done <${REMOTE_INFOR_DIR}/${REMOTE_SERVER}
 
@@ -222,7 +253,17 @@ RunClient() {
     echo "" >>${RESULT_FILE}
     echo ""
 
-    wait
+
+    while true ; do
+        TASK_FINISH_NUM=$( ls ${TASK_FINISH_SUBDIR} | wc -l )
+        if ((TASK_FINISH_NUM == TASK_COUNTER )) ; then 
+            break
+        else 
+            #echo "waiting for tasks between client ${REMOTE_CLIENT} and server ${REMOTE_SERVER} on ${TASK_FINISH_SUBDIR} ... expected ${TASK_COUNTER}, current ${TASK_FINISH_NUM} "
+            sleep 2
+        fi
+    done
+    rm -rf ${TASK_FINISH_SUBDIR}/*
 
 }
 
@@ -254,7 +295,7 @@ RunPerOnHost() {
         OPTIONS+=" -p ${PORT} "
         echo "server on remote ${REMOTE_HOST} for ${REMOTE_INTERFACE} with ${REMOTE_IP}: ${CMD_CLI} ${OPTIONS}"
         (
-            ssh  -p ${ENV_SSH_PORT} ${REMOTE_HOST} "${CMD_CLI} ${OPTIONS} " || true
+            ssh  -p ${ENV_SSH_PORT} ${REMOTE_HOST} "${CMD_CLI} ${OPTIONS} " >/dev/null || true
             #ssh  -p ${ENV_SSH_PORT} ${REMOTE_HOST} "${CMD_CLI} ${OPTIONS} " &>/dev/null
         )&
 
@@ -266,13 +307,13 @@ RunPerOnHost() {
 
 
 TestRdma() {
-    rm -rf ${RESULT_DIR}/*
 
     ALL_HOST_LIST="${1}"
+    ROUND_ID="${2}"
 
     echo " run pair test between: ${ALL_HOST_LIST}   "
 
-    echo "------------------ run server on all devices of each node ------------------"
+    echo "step1: run server on all devices of each node "
     for ADDR in ${ALL_HOST_LIST} ; do
        RunPerOnHost "${ADDR}"
     done
@@ -283,6 +324,13 @@ TestRdma() {
     SERVER_HOST=""
     CLIENT_NAME=""
     SERVER_NAME=""
+    echo 
+    ROUND_TASK_READY_DIR="${TASK_FINISH_DIR}/round-${ROUND_COUNTER}-id-${ROUND_ID}"
+    rm -rf ${ROUND_TASK_READY_DIR}
+    mkdir -p ${ROUND_TASK_READY_DIR}
+
+    echo "step2: run client  "
+    ROUND_TASK_COUNTER=0
     for ADDR in ${ALL_HOST_LIST} ; do
         if [ -z "${CLIENT_HOST}" ] ; then
             CLIENT_HOST="${ADDR}"
@@ -293,27 +341,35 @@ TestRdma() {
             SERVER_HOST="${ADDR}"
             SERVER_NAME=$( GetNodeName ${SERVER_HOST} )
         fi
-        echo "------------------ test communication from ${CLIENT_HOST}/${CLIENT_NAME} to ${SERVER_HOST}/${SERVER_NAME} ------------------"
-        ( RunClient "${CLIENT_HOST}" "${SERVER_HOST}" )&
+        echo ""
+        (( ROUND_TASK_COUNTER = ROUND_TASK_COUNTER + 1 ))
+        #echo "------------------ run client  ${CLIENT_HOST}/${CLIENT_NAME} ===>>  server ${SERVER_HOST}/${SERVER_NAME} ------------------"
+        ( 
+            RunClient "${CLIENT_HOST}" "${SERVER_HOST}" "${ROUND_TASK_COUNTER}"
+            touch ${ROUND_TASK_READY_DIR}/${CLIENT_NAME}-${SERVER_NAME}
+        )&
         CLIENT_HOST=""
         SERVER_HOST=""
         CLIENT_NAME=""
         SERVER_NAME=""
     done
 
-    # (
-    #     sleep ${DURATION} 
-    #     sleep ${DURATION} 
-    #     echo "kill all ib_write_bw and ssh"
-    #     killall ib_write_bw || true
-    #     killall ssh || true
-    # )&
+
     echo "wait for all tests finish"
-    wait
+    while true ; do
+        ROUND_TASK_FINISH_NUM=$( ls ${ROUND_TASK_READY_DIR} | wc -l )
+        if ((ROUND_TASK_FINISH_NUM == ROUND_TASK_COUNTER )) ; then 
+            break
+        else 
+            echo "waiting for round ${ROUND_ID} tasks finish ... expected ${ROUND_TASK_COUNTER}, current ${ROUND_TASK_FINISH_NUM} "
+            sleep 2
+        fi
+    done
+    rm -rf ${ROUND_TASK_READY_DIR}/*
 
 
     echo ""
-    echo "------------------ ${CURRENT_FILENAME} summary -------------------------"
+    echo "------------------ ${CURRENT_FILENAME} summary from ${RESULT_DIR}-------------------------"
     echo ""
     FILE_LIST=$(ls ${RESULT_DIR})
     for FILE_NAME in ${FILE_LIST}; do
@@ -325,35 +381,52 @@ TestRdma() {
 
 }
 
+
 #-------------------------
-DURATION=${DURATION:-"10"}
+DURATION=${DURATION:-"60"}
 LOOP_TIMES=${LOOP_TIMES:-"1"}
 START_PORT=${START_PORT:-"10001"}
 # run all RDMA client asynchronously for each rdma device and each node
-ASYNCHRONOUS=${ASYNCHRONOUS:-"true"}
+ASYNCHRONOUS=${ASYNCHRONOUS:-"false"}
 SAME_NETWORK_TRACK=${SAME_NETWORK_TRACK:-"true"}
 
 RDMA_QOS=${RDMA_QOS:-""}
-BW_CMD_CLI=${BW_CMD_CLI:-"ib_write_bw"}
+BW_CMD_CLI=${BW_CMD_CLI:-"ib_write_lat"}
 ENABLE_RDMA_QOS=${ENABLE_RDMA_QOS:-""}
-BW_CMD_OPTIONS=${BW_CMD_OPTIONS:-"--disable_pcie_relaxed --duration ${DURATION} --report_gbits -F -q 4 "}
+BW_CMD_OPTIONS=${BW_CMD_OPTIONS:-" --duration ${DURATION} -F "}
 [ "${ENABLE_RDMA_QOS}" != "true" ] || BW_CMD_OPTIONS="${BW_CMD_OPTIONS} --rdma_cm"
 [ -z "${RDMA_QOS}" ] || BW_CMD_OPTIONS="${BW_CMD_OPTIONS} --tos ${RDMA_QOS}"
 CMD_CLI="${BW_CMD_CLI}"
 CMD_OPTIONS="${BW_CMD_OPTIONS}"
 
 echo "run ${LOOP_TIMES} times with duration ${DURATION} of ${LOOP_TIMES} round, asynchronously is ${ASYNCHRONOUS}"
-for ((i=1;i<=${LOOP_TIMES};i++)); do
-    echo "===================================== round ${i} ===================================="
+for ((ROUND_COUNTER=1;ROUND_COUNTER<=${LOOP_TIMES};ROUND_COUNTER++)); do
+    echo "===================================== round ${ROUND_COUNTER} : sequential order test ===================================="
 
     # run test on the same network track in sequential order
-    TestRdma "${POD_IP_LIST} ${LOCAL_IP}"
+    echo "run test on sequence order: $( echo "${POD_IP_LIST}" | tr '\n' ' ' )"
+    #echo "${POD_IP_LIST}"
+    TestRdma "${POD_IP_LIST}" "1"
 
-    # run test on the same network track in reverse order
-    # 把 ${LOCAL_IP} 放到前面，${POD_IP_LIST} 放到后面，这样，当是奇数个节点时，避免有主机覆盖不到测试
-    TestRdma "${LOCAL_IP} ${POD_IP_LIST} "
-
+    echo "===================================== round ${ROUND_COUNTER} : reverse order test ===================================="
+    # reverse the stream 
+    REVERSE_LIST=$( echo "${POD_IP_LIST}" | sort -r )
+    echo "run test on reverse order: $( echo "${REVERSE_LIST}" | tr '\n' ' ' )"
+    #echo "${REVERSE_LIST}"
+    TestRdma "${REVERSE_LIST}" "2"
 
     echo ""
 done
 
+
+echo ""
+echo ""
+echo "========================================== summary report ============================================================="
+echo ""
+echo "------------------ ${CURRENT_FILENAME} summary from ${RESULT_DIR}-------------------------"
+echo ""
+FILE_LIST=$(ls ${RESULT_DIR})
+for FILE_NAME in ${FILE_LIST}; do
+    cat ${RESULT_DIR}/${FILE_NAME}
+    echo ""
+done
